language: cpp

services:
  - docker

before_install:
  - 'docker pull ubuntu:14.04'
  - 'docker run -t -i -w $(pwd) -e BUILDPATH=$(pwd) -v $(pwd):$(pwd) ubuntu:14.04 "/bin/bash ./.travis-build.sh"'

notifications:
  recipients:
    - hekark@gmail.com
  email:
    on_success: change
    on_failure: always
