// This file has been generated by Py++.

#include "cbase.h"
// This file has been generated by Py++.

#include "__convenience.pypp.hpp"
#include "__call_policies.pypp.hpp"
#include "cbase.h"
#include "npcevent.h"
#include "srcpy_entities.h"
#include "bone_setup.h"
#include "baseprojectile.h"
#include "basegrenade_shared.h"
#include "takedamageinfo.h"
#include "c_ai_basenpc.h"
#include "soundinfo.h"
#include "saverestore.h"
#include "saverestoretypes.h"
#include "vcollide_parse.h"
#include "iclientvehicle.h"
#include "steam/steamclientpublic.h"
#include "view_shared.h"
#include "c_playerresource.h"
#include "c_breakableprop.h"
#include "tier0/valve_minmax_off.h"
#include "srcpy.h"
#include "tier0/valve_minmax_on.h"
#include "tier0/memdbgon.h"
#include "C_BaseCombatCharacter.pypp.hpp"

namespace bp = boost::python;

struct C_BaseCombatCharacter_wrapper : C_BaseCombatCharacter, bp::wrapper< C_BaseCombatCharacter > {

    C_BaseCombatCharacter_wrapper( )
    : C_BaseCombatCharacter( )
      , bp::wrapper< C_BaseCombatCharacter >(){
        // null constructor
    
    }

    static boost::python::tuple GetGlowEffectColor( ::C_BaseCombatCharacter & inst ){
        float r2;
        float g2;
        float b2;
        inst.GetGlowEffectColor(&r2, &g2, &b2);
        return bp::make_tuple( r2, g2, b2 );
    }

    virtual void OnDataChanged( ::DataUpdateType_t updateType ) {
        PY_OVERRIDE_CHECK( C_BaseCombatCharacter, OnDataChanged )
        PY_OVERRIDE_LOG( _entities, C_BaseCombatCharacter, OnDataChanged )
        bp::override func_OnDataChanged = this->get_override( "OnDataChanged" );
        if( func_OnDataChanged.ptr() != Py_None )
            try {
                func_OnDataChanged( updateType );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseCombatCharacter::OnDataChanged( updateType );
            }
        else
            this->C_BaseCombatCharacter::OnDataChanged( updateType );
    }
    
    void default_OnDataChanged( ::DataUpdateType_t updateType ) {
        C_BaseCombatCharacter::OnDataChanged( updateType );
    }

    virtual void Activate(  ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, Activate )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, Activate )
        bp::override func_Activate = this->get_override( "Activate" );
        if( func_Activate.ptr() != Py_None )
            try {
                func_Activate(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::Activate(  );
            }
        else
            this->C_BaseEntity::Activate(  );
    }
    
    void default_Activate(  ) {
        C_BaseEntity::Activate( );
    }

    virtual void ClientThink(  ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, ClientThink )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, ClientThink )
        bp::override func_ClientThink = this->get_override( "ClientThink" );
        if( func_ClientThink.ptr() != Py_None )
            try {
                func_ClientThink(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::ClientThink(  );
            }
        else
            this->C_BaseEntity::ClientThink(  );
    }
    
    void default_ClientThink(  ) {
        C_BaseEntity::ClientThink( );
    }

    virtual void ComputeWorldSpaceSurroundingBox( ::Vector * pVecWorldMins, ::Vector * pVecWorldMaxs ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, ComputeWorldSpaceSurroundingBox )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, ComputeWorldSpaceSurroundingBox )
        bp::override func_ComputeWorldSpaceSurroundingBox = this->get_override( "ComputeWorldSpaceSurroundingBox" );
        if( func_ComputeWorldSpaceSurroundingBox.ptr() != Py_None )
            try {
                func_ComputeWorldSpaceSurroundingBox( boost::python::ptr(pVecWorldMins), boost::python::ptr(pVecWorldMaxs) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::ComputeWorldSpaceSurroundingBox( pVecWorldMins, pVecWorldMaxs );
            }
        else
            this->C_BaseEntity::ComputeWorldSpaceSurroundingBox( pVecWorldMins, pVecWorldMaxs );
    }
    
    void default_ComputeWorldSpaceSurroundingBox( ::Vector * pVecWorldMins, ::Vector * pVecWorldMaxs ) {
        C_BaseEntity::ComputeWorldSpaceSurroundingBox( pVecWorldMins, pVecWorldMaxs );
    }

    virtual bool CreateVPhysics(  ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, CreateVPhysics )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, CreateVPhysics )
        bp::override func_CreateVPhysics = this->get_override( "CreateVPhysics" );
        if( func_CreateVPhysics.ptr() != Py_None )
            try {
                return func_CreateVPhysics(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseEntity::CreateVPhysics(  );
            }
        else
            return this->C_BaseEntity::CreateVPhysics(  );
    }
    
    bool default_CreateVPhysics(  ) {
        return C_BaseEntity::CreateVPhysics( );
    }

    virtual void DoImpactEffect( ::trace_t & tr, int nDamageType ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, DoImpactEffect )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, DoImpactEffect )
        bp::override func_DoImpactEffect = this->get_override( "DoImpactEffect" );
        if( func_DoImpactEffect.ptr() != Py_None )
            try {
                func_DoImpactEffect( boost::ref(tr), nDamageType );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::DoImpactEffect( tr, nDamageType );
            }
        else
            this->C_BaseEntity::DoImpactEffect( tr, nDamageType );
    }
    
    void default_DoImpactEffect( ::trace_t & tr, int nDamageType ) {
        C_BaseEntity::DoImpactEffect( tr, nDamageType );
    }

    virtual void EndTouch( ::C_BaseEntity * pOther ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, EndTouch )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, EndTouch )
        bp::override func_EndTouch = this->get_override( "EndTouch" );
        if( func_EndTouch.ptr() != Py_None )
            try {
                func_EndTouch( pOther ? pOther->GetPyHandle() : boost::python::object() );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::EndTouch( pOther );
            }
        else
            this->C_BaseEntity::EndTouch( pOther );
    }
    
    void default_EndTouch( ::C_BaseEntity * pOther ) {
        C_BaseEntity::EndTouch( pOther );
    }

    virtual ::CollideType_t GetCollideType(  ) {
        PY_OVERRIDE_CHECK( C_BaseAnimating, GetCollideType )
        PY_OVERRIDE_LOG( _entities, C_BaseAnimating, GetCollideType )
        bp::override func_GetCollideType = this->get_override( "GetCollideType" );
        if( func_GetCollideType.ptr() != Py_None )
            try {
                return func_GetCollideType(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseAnimating::GetCollideType(  );
            }
        else
            return this->C_BaseAnimating::GetCollideType(  );
    }
    
    ::CollideType_t default_GetCollideType(  ) {
        return C_BaseAnimating::GetCollideType( );
    }

    virtual char const * GetTracerType(  ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, GetTracerType )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, GetTracerType )
        bp::override func_GetTracerType = this->get_override( "GetTracerType" );
        if( func_GetTracerType.ptr() != Py_None )
            try {
                return func_GetTracerType(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseEntity::GetTracerType(  );
            }
        else
            return this->C_BaseEntity::GetTracerType(  );
    }
    
    char const * default_GetTracerType(  ) {
        return C_BaseEntity::GetTracerType( );
    }

    virtual bool KeyValue( char const * szKeyName, char const * szValue ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, KeyValue )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, KeyValue )
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, szValue );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseEntity::KeyValue( szKeyName, szValue );
            }
        else
            return this->C_BaseEntity::KeyValue( szKeyName, szValue );
    }
    
    bool default_KeyValue( char const * szKeyName, char const * szValue ) {
        return C_BaseEntity::KeyValue( szKeyName, szValue );
    }

    virtual bool KeyValue( char const * szKeyName, float flValue ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, KeyValue )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, KeyValue )
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, flValue );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseEntity::KeyValue( szKeyName, flValue );
            }
        else
            return this->C_BaseEntity::KeyValue( szKeyName, flValue );
    }
    
    bool default_KeyValue( char const * szKeyName, float flValue ) {
        return C_BaseEntity::KeyValue( szKeyName, flValue );
    }

    virtual bool KeyValue( char const * szKeyName, ::Vector const & vecValue ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, KeyValue )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, KeyValue )
        bp::override func_KeyValue = this->get_override( "KeyValue" );
        if( func_KeyValue.ptr() != Py_None )
            try {
                return func_KeyValue( szKeyName, boost::ref(vecValue) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseEntity::KeyValue( szKeyName, vecValue );
            }
        else
            return this->C_BaseEntity::KeyValue( szKeyName, vecValue );
    }
    
    bool default_KeyValue( char const * szKeyName, ::Vector const & vecValue ) {
        return C_BaseEntity::KeyValue( szKeyName, vecValue );
    }

    virtual void MakeTracer( ::Vector const & vecTracerSrc, ::trace_t const & tr, int iTracerType ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, MakeTracer )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, MakeTracer )
        bp::override func_MakeTracer = this->get_override( "MakeTracer" );
        if( func_MakeTracer.ptr() != Py_None )
            try {
                func_MakeTracer( boost::ref(vecTracerSrc), boost::ref(tr), iTracerType );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::MakeTracer( vecTracerSrc, tr, iTracerType );
            }
        else
            this->C_BaseEntity::MakeTracer( vecTracerSrc, tr, iTracerType );
    }
    
    void default_MakeTracer( ::Vector const & vecTracerSrc, ::trace_t const & tr, int iTracerType ) {
        C_BaseEntity::MakeTracer( vecTracerSrc, tr, iTracerType );
    }

    virtual void NotifyShouldTransmit( ::ShouldTransmitState_t state ) {
        PY_OVERRIDE_CHECK( C_BaseAnimating, NotifyShouldTransmit )
        PY_OVERRIDE_LOG( _entities, C_BaseAnimating, NotifyShouldTransmit )
        bp::override func_NotifyShouldTransmit = this->get_override( "NotifyShouldTransmit" );
        if( func_NotifyShouldTransmit.ptr() != Py_None )
            try {
                func_NotifyShouldTransmit( state );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseAnimating::NotifyShouldTransmit( state );
            }
        else
            this->C_BaseAnimating::NotifyShouldTransmit( state );
    }
    
    void default_NotifyShouldTransmit( ::ShouldTransmitState_t state ) {
        C_BaseAnimating::NotifyShouldTransmit( state );
    }

    virtual void OnRestore(  ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, OnRestore )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, OnRestore )
        bp::override func_OnRestore = this->get_override( "OnRestore" );
        if( func_OnRestore.ptr() != Py_None )
            try {
                func_OnRestore(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::OnRestore(  );
            }
        else
            this->C_BaseEntity::OnRestore(  );
    }
    
    void default_OnRestore(  ) {
        C_BaseEntity::OnRestore( );
    }

    virtual void Precache(  ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, Precache )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, Precache )
        bp::override func_Precache = this->get_override( "Precache" );
        if( func_Precache.ptr() != Py_None )
            try {
                func_Precache(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::Precache(  );
            }
        else
            this->C_BaseEntity::Precache(  );
    }
    
    void default_Precache(  ) {
        C_BaseEntity::Precache( );
    }

    virtual void PyReceiveMessage( ::boost::python::list msg ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, PyReceiveMessage )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, PyReceiveMessage )
        bp::override func_ReceiveMessage = this->get_override( "ReceiveMessage" );
        if( func_ReceiveMessage.ptr() != Py_None )
            try {
                func_ReceiveMessage( msg );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::PyReceiveMessage( msg );
            }
        else
            this->C_BaseEntity::PyReceiveMessage( msg );
    }
    
    void default_ReceiveMessage( ::boost::python::list msg ) {
        C_BaseEntity::PyReceiveMessage( msg );
    }

    virtual int Restore( ::IRestore & restore ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, Restore )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, Restore )
        bp::override func_Restore = this->get_override( "Restore" );
        if( func_Restore.ptr() != Py_None )
            try {
                return func_Restore( boost::ref(restore) );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseEntity::Restore( restore );
            }
        else
            return this->C_BaseEntity::Restore( restore );
    }
    
    int default_Restore( ::IRestore & restore ) {
        return C_BaseEntity::Restore( restore );
    }

    virtual bool ShouldDraw(  ) {
        PY_OVERRIDE_CHECK( C_BaseAnimating, ShouldDraw )
        PY_OVERRIDE_LOG( _entities, C_BaseAnimating, ShouldDraw )
        bp::override func_ShouldDraw = this->get_override( "ShouldDraw" );
        if( func_ShouldDraw.ptr() != Py_None )
            try {
                return func_ShouldDraw(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                return this->C_BaseAnimating::ShouldDraw(  );
            }
        else
            return this->C_BaseAnimating::ShouldDraw(  );
    }
    
    bool default_ShouldDraw(  ) {
        return C_BaseAnimating::ShouldDraw( );
    }

    virtual void Simulate(  ) {
        PY_OVERRIDE_CHECK( C_BaseAnimating, Simulate )
        PY_OVERRIDE_LOG( _entities, C_BaseAnimating, Simulate )
        bp::override func_Simulate = this->get_override( "Simulate" );
        if( func_Simulate.ptr() != Py_None )
            try {
                func_Simulate(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseAnimating::Simulate(  );
            }
        else
            this->C_BaseAnimating::Simulate(  );
    }
    
    void default_Simulate(  ) {
        C_BaseAnimating::Simulate( );
    }

    virtual void Spawn(  ) {
        PY_OVERRIDE_CHECK( C_BaseFlex, Spawn )
        PY_OVERRIDE_LOG( _entities, C_BaseFlex, Spawn )
        bp::override func_Spawn = this->get_override( "Spawn" );
        if( func_Spawn.ptr() != Py_None )
            try {
                func_Spawn(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseFlex::Spawn(  );
            }
        else
            this->C_BaseFlex::Spawn(  );
    }
    
    void default_Spawn(  ) {
        C_BaseFlex::Spawn( );
    }

    virtual void StartTouch( ::C_BaseEntity * pOther ) {
        PY_OVERRIDE_CHECK( C_BaseEntity, StartTouch )
        PY_OVERRIDE_LOG( _entities, C_BaseEntity, StartTouch )
        bp::override func_StartTouch = this->get_override( "StartTouch" );
        if( func_StartTouch.ptr() != Py_None )
            try {
                func_StartTouch( pOther ? pOther->GetPyHandle() : boost::python::object() );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseEntity::StartTouch( pOther );
            }
        else
            this->C_BaseEntity::StartTouch( pOther );
    }
    
    void default_StartTouch( ::C_BaseEntity * pOther ) {
        C_BaseEntity::StartTouch( pOther );
    }

    virtual void UpdateOnRemove(  ) {
        PY_OVERRIDE_CHECK( C_BaseAnimating, UpdateOnRemove )
        PY_OVERRIDE_LOG( _entities, C_BaseAnimating, UpdateOnRemove )
        bp::override func_UpdateOnRemove = this->get_override( "UpdateOnRemove" );
        if( func_UpdateOnRemove.ptr() != Py_None )
            try {
                func_UpdateOnRemove(  );
            } catch(bp::error_already_set &) {
                PyErr_Print();
                this->C_BaseAnimating::UpdateOnRemove(  );
            }
        else
            this->C_BaseAnimating::UpdateOnRemove(  );
    }
    
    void default_UpdateOnRemove(  ) {
        C_BaseAnimating::UpdateOnRemove( );
    }

    virtual PyObject *GetPySelf() const { return bp::detail::wrapper_base_::get_owner(*this); }

    virtual ClientClass* GetClientClass() {
    #if defined(_WIN32)
            if( GetCurrentThreadId() != g_hPythonThreadID )
                return C_BaseCombatCharacter::GetClientClass();
    #endif // _WIN32
            if( PyObject_HasAttrString(GetPyInstance().ptr(), "pyClientClass") )
            {
                try
                {
                    ClientClass *pClientClass = boost::python::extract<ClientClass *>( GetPyInstance().attr("pyClientClass") );
                    if( pClientClass )
                        return pClientClass;
                }
                catch( bp::error_already_set & ) 
                {
                    PyErr_Print();
                }
            }
            return C_BaseCombatCharacter::GetClientClass();
        }

    static int m_lifeState_Get( C_BaseCombatCharacter const & inst ) { return inst.m_lifeState; }

    static void m_lifeState_Set( C_BaseCombatCharacter & inst, int val ) { inst.m_lifeState = val; }

    static int m_takedamage_Get( C_BaseCombatCharacter const & inst ) { return inst.m_takedamage; }

    static void m_takedamage_Set( C_BaseCombatCharacter & inst, int val ) { inst.m_takedamage = val; }

    static int m_nSkin_Get( C_BaseCombatCharacter const & inst ) { return inst.m_nSkin; }

    static void m_nSkin_Set( C_BaseCombatCharacter & inst, int val ) { inst.m_nSkin = val; }

};

void register_C_BaseCombatCharacter_class(){

    { //::C_BaseCombatCharacter
        typedef bp::class_< C_BaseCombatCharacter_wrapper, bp::bases< C_BaseFlex >, boost::noncopyable > C_BaseCombatCharacter_exposer_t;
        C_BaseCombatCharacter_exposer_t C_BaseCombatCharacter_exposer = C_BaseCombatCharacter_exposer_t( "C_BaseCombatCharacter", bp::init< >() );
        bp::scope C_BaseCombatCharacter_scope( C_BaseCombatCharacter_exposer );
        bp::enum_< C_BaseCombatCharacter::FieldOfViewCheckType>("FieldOfViewCheckType")
            .value("USE_FOV", C_BaseCombatCharacter::USE_FOV)
            .value("DISREGARD_FOV", C_BaseCombatCharacter::DISREGARD_FOV)
            .export_values()
            ;
        bp::enum_< C_BaseCombatCharacter::LineOfSightCheckType>("LineOfSightCheckType")
            .value("IGNORE_NOTHING", C_BaseCombatCharacter::IGNORE_NOTHING)
            .value("IGNORE_ACTORS", C_BaseCombatCharacter::IGNORE_ACTORS)
            .export_values()
            ;
        { //::C_BaseCombatCharacter::BloodColor
        
            typedef int ( ::C_BaseCombatCharacter::*BloodColor_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "BloodColor"
                , BloodColor_function_type( &::C_BaseCombatCharacter::BloodColor ) );
        
        }
        { //::C_BaseCombatCharacter::DoMuzzleFlash
        
            typedef void ( ::C_BaseCombatCharacter::*DoMuzzleFlash_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "DoMuzzleFlash"
                , DoMuzzleFlash_function_type( &::C_BaseCombatCharacter::DoMuzzleFlash ) );
        
        }
        { //::C_BaseCombatCharacter::GetAmmoCount
        
            typedef int ( ::C_BaseCombatCharacter::*GetAmmoCount_function_type)( int ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "GetAmmoCount"
                , GetAmmoCount_function_type( &::C_BaseCombatCharacter::GetAmmoCount )
                , ( bp::arg("iAmmoIndex") ) );
        
        }
        { //::C_BaseCombatCharacter::GetAmmoCount
        
            typedef int ( ::C_BaseCombatCharacter::*GetAmmoCount_function_type)( char * ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "GetAmmoCount"
                , GetAmmoCount_function_type( &::C_BaseCombatCharacter::GetAmmoCount )
                , ( bp::arg("szName") ) );
        
        }
        { //::C_BaseCombatCharacter::GetGlowEffectColor
        
            typedef boost::python::tuple ( *GetGlowEffectColor_function_type )( ::C_BaseCombatCharacter & );
            
            C_BaseCombatCharacter_exposer.def( 
                "GetGlowEffectColor"
                , GetGlowEffectColor_function_type( &C_BaseCombatCharacter_wrapper::GetGlowEffectColor )
                , ( bp::arg("inst") ) );
        
        }
        { //::C_BaseCombatCharacter::GetNextAttack
        
            typedef float ( ::C_BaseCombatCharacter::*GetNextAttack_function_type)(  ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "GetNextAttack"
                , GetNextAttack_function_type( &::C_BaseCombatCharacter::GetNextAttack ) );
        
        }
        { //::C_BaseCombatCharacter::GetWeapon
        
            typedef ::C_BaseCombatWeapon * ( ::C_BaseCombatCharacter::*GetWeapon_function_type)( int ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "GetWeapon"
                , GetWeapon_function_type( &::C_BaseCombatCharacter::GetWeapon )
                , ( bp::arg("i") )
                , bp::return_value_policy< bp::return_by_value >() );
        
        }
        { //::C_BaseCombatCharacter::IsAbleToSee
        
            typedef bool ( ::C_BaseCombatCharacter::*IsAbleToSee_function_type)( ::C_BaseEntity const *,::C_BaseCombatCharacter::FieldOfViewCheckType ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsAbleToSee"
                , IsAbleToSee_function_type( &::C_BaseCombatCharacter::IsAbleToSee )
                , ( bp::arg("entity"), bp::arg("checkFOV") ) );
        
        }
        { //::C_BaseCombatCharacter::IsAbleToSee
        
            typedef bool ( ::C_BaseCombatCharacter::*IsAbleToSee_function_type)( ::C_BaseCombatCharacter *,::C_BaseCombatCharacter::FieldOfViewCheckType ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsAbleToSee"
                , IsAbleToSee_function_type( &::C_BaseCombatCharacter::IsAbleToSee )
                , ( bp::arg("pBCC"), bp::arg("checkFOV") ) );
        
        }
        { //::C_BaseCombatCharacter::IsBaseCombatCharacter
        
            typedef bool ( ::C_BaseCombatCharacter::*IsBaseCombatCharacter_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsBaseCombatCharacter"
                , IsBaseCombatCharacter_function_type( &::C_BaseCombatCharacter::IsBaseCombatCharacter ) );
        
        }
        { //::C_BaseCombatCharacter::IsClientSideGlowEnabled
        
            typedef bool ( ::C_BaseCombatCharacter::*IsClientSideGlowEnabled_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsClientSideGlowEnabled"
                , IsClientSideGlowEnabled_function_type( &::C_BaseCombatCharacter::IsClientSideGlowEnabled ) );
        
        }
        { //::C_BaseCombatCharacter::IsInFieldOfView
        
            typedef bool ( ::C_BaseCombatCharacter::*IsInFieldOfView_function_type)( ::C_BaseEntity * ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsInFieldOfView"
                , IsInFieldOfView_function_type( &::C_BaseCombatCharacter::IsInFieldOfView )
                , ( bp::arg("entity") ) );
        
        }
        { //::C_BaseCombatCharacter::IsInFieldOfView
        
            typedef bool ( ::C_BaseCombatCharacter::*IsInFieldOfView_function_type)( ::Vector const & ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsInFieldOfView"
                , IsInFieldOfView_function_type( &::C_BaseCombatCharacter::IsInFieldOfView )
                , ( bp::arg("pos") ) );
        
        }
        { //::C_BaseCombatCharacter::IsLineOfSightClear
        
            typedef bool ( ::C_BaseCombatCharacter::*IsLineOfSightClear_function_type)( ::C_BaseEntity *,::C_BaseCombatCharacter::LineOfSightCheckType ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsLineOfSightClear"
                , IsLineOfSightClear_function_type( &::C_BaseCombatCharacter::IsLineOfSightClear )
                , ( bp::arg("entity"), bp::arg("checkType")=::C_BaseCombatCharacter::LineOfSightCheckType::IGNORE_NOTHING ) );
        
        }
        { //::C_BaseCombatCharacter::IsLineOfSightClear
        
            typedef bool ( ::C_BaseCombatCharacter::*IsLineOfSightClear_function_type)( ::Vector const &,::C_BaseCombatCharacter::LineOfSightCheckType,::C_BaseEntity * ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsLineOfSightClear"
                , IsLineOfSightClear_function_type( &::C_BaseCombatCharacter::IsLineOfSightClear )
                , ( bp::arg("pos"), bp::arg("checkType")=::C_BaseCombatCharacter::LineOfSightCheckType::IGNORE_NOTHING, bp::arg("entityToIgnore")=bp::object() ) );
        
        }
        { //::C_BaseCombatCharacter::IsLookingTowards
        
            typedef bool ( ::C_BaseCombatCharacter::*IsLookingTowards_function_type)( ::C_BaseEntity const *,float ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsLookingTowards"
                , IsLookingTowards_function_type( &::C_BaseCombatCharacter::IsLookingTowards )
                , ( bp::arg("target"), bp::arg("cosTolerance")=0.899999976F ) );
        
        }
        { //::C_BaseCombatCharacter::IsLookingTowards
        
            typedef bool ( ::C_BaseCombatCharacter::*IsLookingTowards_function_type)( ::Vector const &,float ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "IsLookingTowards"
                , IsLookingTowards_function_type( &::C_BaseCombatCharacter::IsLookingTowards )
                , ( bp::arg("target"), bp::arg("cosTolerance")=0.899999976F ) );
        
        }
        { //::C_BaseCombatCharacter::OnDataChanged
        
            typedef void ( ::C_BaseCombatCharacter::*OnDataChanged_function_type)( ::DataUpdateType_t ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_OnDataChanged_function_type)( ::DataUpdateType_t ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "OnDataChanged"
                , OnDataChanged_function_type(&::C_BaseCombatCharacter::OnDataChanged)
                , default_OnDataChanged_function_type(&C_BaseCombatCharacter_wrapper::default_OnDataChanged)
                , ( bp::arg("updateType") ) );
        
        }
        { //::C_BaseCombatCharacter::OnPreDataChanged
        
            typedef void ( ::C_BaseCombatCharacter::*OnPreDataChanged_function_type)( ::DataUpdateType_t ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "OnPreDataChanged"
                , OnPreDataChanged_function_type( &::C_BaseCombatCharacter::OnPreDataChanged )
                , ( bp::arg("updateType") ) );
        
        }
        { //::C_BaseCombatCharacter::RemoveAllAmmo
        
            typedef void ( ::C_BaseCombatCharacter::*RemoveAllAmmo_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "RemoveAllAmmo"
                , RemoveAllAmmo_function_type( &::C_BaseCombatCharacter::RemoveAllAmmo ) );
        
        }
        { //::C_BaseCombatCharacter::RemoveAmmo
        
            typedef void ( ::C_BaseCombatCharacter::*RemoveAmmo_function_type)( int,int ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "RemoveAmmo"
                , RemoveAmmo_function_type( &::C_BaseCombatCharacter::RemoveAmmo )
                , ( bp::arg("iCount"), bp::arg("iAmmoIndex") ) );
        
        }
        { //::C_BaseCombatCharacter::RemoveAmmo
        
            typedef void ( ::C_BaseCombatCharacter::*RemoveAmmo_function_type)( int,char const * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "RemoveAmmo"
                , RemoveAmmo_function_type( &::C_BaseCombatCharacter::RemoveAmmo )
                , ( bp::arg("iCount"), bp::arg("szName") ) );
        
        }
        { //::C_BaseCombatCharacter::SetAmmoCount
        
            typedef void ( ::C_BaseCombatCharacter::*SetAmmoCount_function_type)( int,int ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "SetAmmoCount"
                , SetAmmoCount_function_type( &::C_BaseCombatCharacter::SetAmmoCount )
                , ( bp::arg("iCount"), bp::arg("iAmmoIndex") ) );
        
        }
        { //::C_BaseCombatCharacter::SetBloodColor
        
            typedef void ( ::C_BaseCombatCharacter::*SetBloodColor_function_type)( int ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "SetBloodColor"
                , SetBloodColor_function_type( &::C_BaseCombatCharacter::SetBloodColor )
                , ( bp::arg("nBloodColor") ) );
        
        }
        { //::C_BaseCombatCharacter::SetClientSideGlowEnabled
        
            typedef void ( ::C_BaseCombatCharacter::*SetClientSideGlowEnabled_function_type)( bool ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "SetClientSideGlowEnabled"
                , SetClientSideGlowEnabled_function_type( &::C_BaseCombatCharacter::SetClientSideGlowEnabled )
                , ( bp::arg("bEnabled") ) );
        
        }
        { //::C_BaseCombatCharacter::SetNextAttack
        
            typedef void ( ::C_BaseCombatCharacter::*SetNextAttack_function_type)( float ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "SetNextAttack"
                , SetNextAttack_function_type( &::C_BaseCombatCharacter::SetNextAttack )
                , ( bp::arg("flWait") ) );
        
        }
        { //::C_BaseCombatCharacter::SwitchToNextBestWeapon
        
            typedef bool ( ::C_BaseCombatCharacter::*SwitchToNextBestWeapon_function_type)( ::C_BaseCombatWeapon * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "SwitchToNextBestWeapon"
                , SwitchToNextBestWeapon_function_type( &::C_BaseCombatCharacter::SwitchToNextBestWeapon )
                , ( bp::arg("pCurrent") ) );
        
        }
        { //::C_BaseCombatCharacter::WeaponCount
        
            typedef int ( ::C_BaseCombatCharacter::*WeaponCount_function_type)(  ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "WeaponCount"
                , WeaponCount_function_type( &::C_BaseCombatCharacter::WeaponCount ) );
        
        }
        { //::C_BaseCombatCharacter::Weapon_CanSwitchTo
        
            typedef bool ( ::C_BaseCombatCharacter::*Weapon_CanSwitchTo_function_type)( ::C_BaseCombatWeapon * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Weapon_CanSwitchTo"
                , Weapon_CanSwitchTo_function_type( &::C_BaseCombatCharacter::Weapon_CanSwitchTo )
                , ( bp::arg("pWeapon") ) );
        
        }
        { //::C_BaseCombatCharacter::Weapon_OwnsThisType
        
            typedef ::C_BaseCombatWeapon * ( ::C_BaseCombatCharacter::*Weapon_OwnsThisType_function_type)( char const *,int ) const;
            
            C_BaseCombatCharacter_exposer.def( 
                "Weapon_OwnsThisType"
                , Weapon_OwnsThisType_function_type( &::C_BaseCombatCharacter::Weapon_OwnsThisType )
                , ( bp::arg("pszWeapon"), bp::arg("iSubType")=(int)(0) )
                , bp::return_value_policy< bp::return_by_value >() );
        
        }
        { //::C_BaseCombatCharacter::Weapon_Switch
        
            typedef bool ( ::C_BaseCombatCharacter::*Weapon_Switch_function_type)( ::C_BaseCombatWeapon *,int ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Weapon_Switch"
                , Weapon_Switch_function_type( &::C_BaseCombatCharacter::Weapon_Switch )
                , ( bp::arg("pWeapon"), bp::arg("viewmodelindex")=(int)(0) ) );
        
        }
        { //::C_BaseEntity::Activate
        
            typedef void ( ::C_BaseEntity::*Activate_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_Activate_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Activate"
                , Activate_function_type(&::C_BaseEntity::Activate)
                , default_Activate_function_type(&C_BaseCombatCharacter_wrapper::default_Activate) );
        
        }
        { //::C_BaseEntity::ClientThink
        
            typedef void ( ::C_BaseEntity::*ClientThink_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_ClientThink_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "ClientThink"
                , ClientThink_function_type(&::C_BaseEntity::ClientThink)
                , default_ClientThink_function_type(&C_BaseCombatCharacter_wrapper::default_ClientThink) );
        
        }
        { //::C_BaseEntity::ComputeWorldSpaceSurroundingBox
        
            typedef void ( ::C_BaseEntity::*ComputeWorldSpaceSurroundingBox_function_type)( ::Vector *,::Vector * ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_ComputeWorldSpaceSurroundingBox_function_type)( ::Vector *,::Vector * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "ComputeWorldSpaceSurroundingBox"
                , ComputeWorldSpaceSurroundingBox_function_type(&::C_BaseEntity::ComputeWorldSpaceSurroundingBox)
                , default_ComputeWorldSpaceSurroundingBox_function_type(&C_BaseCombatCharacter_wrapper::default_ComputeWorldSpaceSurroundingBox)
                , ( bp::arg("pVecWorldMins"), bp::arg("pVecWorldMaxs") ) );
        
        }
        { //::C_BaseEntity::CreateVPhysics
        
            typedef bool ( ::C_BaseEntity::*CreateVPhysics_function_type)(  ) ;
            typedef bool ( C_BaseCombatCharacter_wrapper::*default_CreateVPhysics_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "CreateVPhysics"
                , CreateVPhysics_function_type(&::C_BaseEntity::CreateVPhysics)
                , default_CreateVPhysics_function_type(&C_BaseCombatCharacter_wrapper::default_CreateVPhysics) );
        
        }
        { //::C_BaseEntity::DoImpactEffect
        
            typedef void ( ::C_BaseEntity::*DoImpactEffect_function_type)( ::trace_t &,int ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_DoImpactEffect_function_type)( ::trace_t &,int ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "DoImpactEffect"
                , DoImpactEffect_function_type(&::C_BaseEntity::DoImpactEffect)
                , default_DoImpactEffect_function_type(&C_BaseCombatCharacter_wrapper::default_DoImpactEffect)
                , ( bp::arg("tr"), bp::arg("nDamageType") ) );
        
        }
        { //::C_BaseEntity::EndTouch
        
            typedef void ( ::C_BaseEntity::*EndTouch_function_type)( ::C_BaseEntity * ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_EndTouch_function_type)( ::C_BaseEntity * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "EndTouch"
                , EndTouch_function_type(&::C_BaseEntity::EndTouch)
                , default_EndTouch_function_type(&C_BaseCombatCharacter_wrapper::default_EndTouch)
                , ( bp::arg("pOther") ) );
        
        }
        { //::C_BaseAnimating::GetCollideType
        
            typedef ::CollideType_t ( ::C_BaseAnimating::*GetCollideType_function_type)(  ) ;
            typedef ::CollideType_t ( C_BaseCombatCharacter_wrapper::*default_GetCollideType_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "GetCollideType"
                , GetCollideType_function_type(&::C_BaseAnimating::GetCollideType)
                , default_GetCollideType_function_type(&C_BaseCombatCharacter_wrapper::default_GetCollideType) );
        
        }
        { //::C_BaseEntity::GetTracerType
        
            typedef char const * ( ::C_BaseEntity::*GetTracerType_function_type)(  ) ;
            typedef char const * ( C_BaseCombatCharacter_wrapper::*default_GetTracerType_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "GetTracerType"
                , GetTracerType_function_type(&::C_BaseEntity::GetTracerType)
                , default_GetTracerType_function_type(&C_BaseCombatCharacter_wrapper::default_GetTracerType) );
        
        }
        { //::C_BaseEntity::KeyValue
        
            typedef bool ( ::C_BaseEntity::*KeyValue_function_type)( char const *,char const * ) ;
            typedef bool ( C_BaseCombatCharacter_wrapper::*default_KeyValue_function_type)( char const *,char const * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::C_BaseEntity::KeyValue)
                , default_KeyValue_function_type(&C_BaseCombatCharacter_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("szValue") ) );
        
        }
        { //::C_BaseEntity::KeyValue
        
            typedef bool ( ::C_BaseEntity::*KeyValue_function_type)( char const *,float ) ;
            typedef bool ( C_BaseCombatCharacter_wrapper::*default_KeyValue_function_type)( char const *,float ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::C_BaseEntity::KeyValue)
                , default_KeyValue_function_type(&C_BaseCombatCharacter_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("flValue") ) );
        
        }
        { //::C_BaseEntity::KeyValue
        
            typedef bool ( ::C_BaseEntity::*KeyValue_function_type)( char const *,::Vector const & ) ;
            typedef bool ( C_BaseCombatCharacter_wrapper::*default_KeyValue_function_type)( char const *,::Vector const & ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "KeyValue"
                , KeyValue_function_type(&::C_BaseEntity::KeyValue)
                , default_KeyValue_function_type(&C_BaseCombatCharacter_wrapper::default_KeyValue)
                , ( bp::arg("szKeyName"), bp::arg("vecValue") ) );
        
        }
        { //::C_BaseEntity::MakeTracer
        
            typedef void ( ::C_BaseEntity::*MakeTracer_function_type)( ::Vector const &,::trace_t const &,int ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_MakeTracer_function_type)( ::Vector const &,::trace_t const &,int ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "MakeTracer"
                , MakeTracer_function_type(&::C_BaseEntity::MakeTracer)
                , default_MakeTracer_function_type(&C_BaseCombatCharacter_wrapper::default_MakeTracer)
                , ( bp::arg("vecTracerSrc"), bp::arg("tr"), bp::arg("iTracerType") ) );
        
        }
        { //::C_BaseAnimating::NotifyShouldTransmit
        
            typedef void ( ::C_BaseAnimating::*NotifyShouldTransmit_function_type)( ::ShouldTransmitState_t ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_NotifyShouldTransmit_function_type)( ::ShouldTransmitState_t ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "NotifyShouldTransmit"
                , NotifyShouldTransmit_function_type(&::C_BaseAnimating::NotifyShouldTransmit)
                , default_NotifyShouldTransmit_function_type(&C_BaseCombatCharacter_wrapper::default_NotifyShouldTransmit)
                , ( bp::arg("state") ) );
        
        }
        { //::C_BaseEntity::OnRestore
        
            typedef void ( ::C_BaseEntity::*OnRestore_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_OnRestore_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "OnRestore"
                , OnRestore_function_type(&::C_BaseEntity::OnRestore)
                , default_OnRestore_function_type(&C_BaseCombatCharacter_wrapper::default_OnRestore) );
        
        }
        { //::C_BaseEntity::Precache
        
            typedef void ( ::C_BaseEntity::*Precache_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_Precache_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Precache"
                , Precache_function_type(&::C_BaseEntity::Precache)
                , default_Precache_function_type(&C_BaseCombatCharacter_wrapper::default_Precache) );
        
        }
        { //::C_BaseEntity::PyReceiveMessage
        
            typedef void ( ::C_BaseEntity::*ReceiveMessage_function_type)( ::boost::python::list ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_ReceiveMessage_function_type)( ::boost::python::list ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "ReceiveMessage"
                , ReceiveMessage_function_type(&::C_BaseEntity::PyReceiveMessage)
                , default_ReceiveMessage_function_type(&C_BaseCombatCharacter_wrapper::default_ReceiveMessage)
                , ( bp::arg("msg") ) );
        
        }
        { //::C_BaseEntity::Restore
        
            typedef int ( ::C_BaseEntity::*Restore_function_type)( ::IRestore & ) ;
            typedef int ( C_BaseCombatCharacter_wrapper::*default_Restore_function_type)( ::IRestore & ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Restore"
                , Restore_function_type(&::C_BaseEntity::Restore)
                , default_Restore_function_type(&C_BaseCombatCharacter_wrapper::default_Restore)
                , ( bp::arg("restore") ) );
        
        }
        { //::C_BaseAnimating::ShouldDraw
        
            typedef bool ( ::C_BaseAnimating::*ShouldDraw_function_type)(  ) ;
            typedef bool ( C_BaseCombatCharacter_wrapper::*default_ShouldDraw_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "ShouldDraw"
                , ShouldDraw_function_type(&::C_BaseAnimating::ShouldDraw)
                , default_ShouldDraw_function_type(&C_BaseCombatCharacter_wrapper::default_ShouldDraw) );
        
        }
        { //::C_BaseAnimating::Simulate
        
            typedef void ( ::C_BaseAnimating::*Simulate_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_Simulate_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Simulate"
                , Simulate_function_type(&::C_BaseAnimating::Simulate)
                , default_Simulate_function_type(&C_BaseCombatCharacter_wrapper::default_Simulate) );
        
        }
        { //::C_BaseFlex::Spawn
        
            typedef void ( ::C_BaseFlex::*Spawn_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_Spawn_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "Spawn"
                , Spawn_function_type(&::C_BaseFlex::Spawn)
                , default_Spawn_function_type(&C_BaseCombatCharacter_wrapper::default_Spawn) );
        
        }
        { //::C_BaseEntity::StartTouch
        
            typedef void ( ::C_BaseEntity::*StartTouch_function_type)( ::C_BaseEntity * ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_StartTouch_function_type)( ::C_BaseEntity * ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "StartTouch"
                , StartTouch_function_type(&::C_BaseEntity::StartTouch)
                , default_StartTouch_function_type(&C_BaseCombatCharacter_wrapper::default_StartTouch)
                , ( bp::arg("pOther") ) );
        
        }
        { //::C_BaseAnimating::UpdateOnRemove
        
            typedef void ( ::C_BaseAnimating::*UpdateOnRemove_function_type)(  ) ;
            typedef void ( C_BaseCombatCharacter_wrapper::*default_UpdateOnRemove_function_type)(  ) ;
            
            C_BaseCombatCharacter_exposer.def( 
                "UpdateOnRemove"
                , UpdateOnRemove_function_type(&::C_BaseAnimating::UpdateOnRemove)
                , default_UpdateOnRemove_function_type(&C_BaseCombatCharacter_wrapper::default_UpdateOnRemove) );
        
        }
        { //property "activeweapon"[fget=::C_BaseCombatCharacter::GetActiveWeapon]
        
            typedef ::C_BaseCombatWeapon * ( ::C_BaseCombatCharacter::*fget)(  ) const;
            
            C_BaseCombatCharacter_exposer.add_property( 
                "activeweapon"
                , bp::make_function( 
                      fget( &::C_BaseCombatCharacter::GetActiveWeapon )
                    , bp::return_value_policy< bp::return_by_value >() )  );
        
        }
        C_BaseCombatCharacter_exposer.add_property( "lifestate", &C_BaseCombatCharacter_wrapper::m_lifeState_Get, &C_BaseCombatCharacter_wrapper::m_lifeState_Set );
        C_BaseCombatCharacter_exposer.add_property( "takedamage", &C_BaseCombatCharacter_wrapper::m_takedamage_Get, &C_BaseCombatCharacter_wrapper::m_takedamage_Set );
        C_BaseCombatCharacter_exposer.add_property( "skin", &C_BaseCombatCharacter_wrapper::m_nSkin_Get, &C_BaseCombatCharacter_wrapper::m_nSkin_Set );
    }

}

