version: 2
jobs:
  build:
    docker:
      - image: hekar/luminousforts-ci:latest
    steps:
      - checkout
      - run:
          command: |
            cd ./mp/src
            ./createallprojects
            make -f everything.mak
      - persist_to_workspace:
          root: .
          paths:
            - mp/
      
  publish:
    docker:
      - image: hekar/luminousforts-ci-commit:latest
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          command: |
            cd /tmp
            git clone --depth 1 https://${GITHUB_TOKEN}@github.com/hekar/luminousforts.git
            rsync --progress -v /tmp/project/mp/game/mod_hl2mp/bin/* ./luminousforts/bin/
      - deploy:
          name: Trigger docs deployment
          working_directory: /tmp/luminousforts
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "hekark@gmail.com"
            git config user.name "LF Deployment Bot"
            git add ./bin/*.so
            git commit -m "Automated Binaries ${CIRCLE_BUILD_NUM}"
            git push -q https://${GITHUB_TOKEN}@github.com/hekar/luminousforts.git master
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
